//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.24 at 11:50:18 AM MSK 
//


package request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AllowedAtribute.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AllowedAtribute">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="JOURNAL"/>
 *     &lt;enumeration value="SUMMARY"/>
 *     &lt;enumeration value="PDF"/>
 *     &lt;enumeration value="BIBTEX"/>
 *     &lt;enumeration value="SUBJECT"/>
 *     &lt;enumeration value="PAGES"/>
 *     &lt;enumeration value="KEYWORDS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AllowedAtribute")
@XmlEnum
public enum AllowedAtribute {

    JOURNAL,
    SUMMARY,
    PDF,
    BIBTEX,
    SUBJECT,
    PAGES,
    KEYWORDS;

    public String value() {
        return name();
    }

    public static AllowedAtribute fromValue(String v) {
        return valueOf(v);
    }

}
