//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.24 at 11:50:18 AM MSK 
//


package request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="atribute" type="{http://www.example.org/request/}AllowedAtribute"/>
 *         &lt;element name="publications" type="{http://www.example.org/request/}Publication" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "atribute",
    "publications"
})
@XmlRootElement(name = "specifyingPublication")
public class SpecifyingPublication {

    @XmlElement(required = true)
    protected AllowedAtribute atribute;
    @XmlElement(required = true)
    protected List<Publication> publications;

    /**
     * Gets the value of the atribute property.
     * 
     * @return
     *     possible object is
     *     {@link AllowedAtribute }
     *     
     */
    public AllowedAtribute getAtribute() {
        return atribute;
    }

    /**
     * Sets the value of the atribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllowedAtribute }
     *     
     */
    public void setAtribute(AllowedAtribute value) {
        this.atribute = value;
    }

    /**
     * Gets the value of the publications property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publications property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublications().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Publication }
     * 
     * 
     */
    public List<Publication> getPublications() {
        if (publications == null) {
            publications = new ArrayList<Publication>();
        }
        return this.publications;
    }

}
